name: Download latest data
on:
  schedule:
  - cron: 53 0/3 * * *
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DATA_PAT }}

      - uses: haskell/actions/setup@v2
        id: setup
        with:
          ghc-version: '9.2.8'
          cabal-version: '3.10.1.0'

      - name: Cache .cabal
        uses: actions/cache@v3
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: cabal-${{ hashFiles('cabal.project') }}-${{ hashFiles('**/*.cabal') }}

      - name: download
        run: |
          cabal update
          cabal run pw-scraper -- -p data scrape

      - name: add commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

