name: Summarise the data
on:
  schedule:
  - cron: 21 4 * * *
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DATA_PAT }}

      - name: Update summary files
        run: ./summarise-data.sh

      - name: add commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

